### ISSUE TITLE
Provide instructions or a script for the standalone language server

### ISSUE THREAD

**Issue by bolinfest** [sourcegraph/go-langserver#135]
I tried to figure it out from https://github.com/sourcegraph/go-langserver/blob/master/vscode/package.json, but `npm run compile` gives me errors about `$GOPATH` not being set.

**Comment by bolinfest** [comment]
Here's what I ended up doing:

```
export GOPATH=$HOME/go
mkdir -p $GOPATH
http_proxy=<i-happen-to-need-a-proxy> go get github.com/sourcegraph/go-langserver/la
ngserver/cmd/langserver-go
```

I suppose if you're used to building stuff with Go, this is obvious, but the only Go code I've built in the past was with Bazel, so I didn't have to do any of this stuff.

**Comment by bolinfest** [comment]
I should mention that the binary can then be run from `$GOPATH/bin/langserver-go`.

Though this doesn't explain how I could make a local change and then rebuild that version. This just builds what's public on GitHub, right?

**Comment by keegancsmith** [comment]
Yeah sorry this is all very poorly documented, I will update the README a bit. Some notes before that though:

* The vscode integration here is very experimental, and is not used much.
* There is also an experimental branch of `vscode-go` which uses this language server at https://github.com/Microsoft/vscode-go/tree/langserver (the diff with master can explain how to use the server)
* I will add `go get` instructions. Yeah it is the usual way to build and get go code.
* I will also add `go install` instructions. That is probably what you want for local changes.
* The language server itself is used in production at sourcegraph.com

**Comment by ramya-rao-a** [comment]
Note: https://github.com/Microsoft/vscode-go/tree/langserver doesn't exist anymore. The integration of the vscode-go extension with the language server is now available in master
