### ISSUE TITLE
Active Parameter in Signature Help gets incremented before typing comma

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#136]
I was testing the integration of the language server with VS Code.

Take the example of `math.max()`. This takes 2 parameters
When cursor is inside the brackets, active parameter is shown as the first one. 

<img width="393" alt="screen shot 2017-02-05 at 6 31 24 pm" src="https://cloud.githubusercontent.com/assets/16890566/22632831/7001b3a8-ebd1-11e6-9a60-690d07395862.png">

Type a single digit, the second parameter becomes the active parameter.

<img width="417" alt="screen shot 2017-02-05 at 6 31 39 pm" src="https://cloud.githubusercontent.com/assets/16890566/22632834/71d5cc00-ebd1-11e6-8042-2ac50460269d.png">

Expected: The second parameter becomes the active one only after pressing comma

**Comment by keegancsmith** [comment]
I'll take a look before EOW

**Comment by ramya-rao-a** [comment]
@keegancsmith I have a PR #153 out to fix this. It would be great to fix this issue fixed before I ship the integration with VS Code next week
