### ISSUE TITLE
Signature Information is missing doc in Signature Help

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#137]
Using VS Code to test the integration with language server

The SignatureInformation is made up of label, docs and params.

<img width="565" alt="screen shot 2017-02-05 at 6 36 27 pm" src="https://cloud.githubusercontent.com/assets/16890566/22632909/0a5cf7c8-ebd2-11e6-9eb9-044bcf0e3a37.png">

The SignatureHelpProvider by the language server does not send the docs at the moment.
And so, the signature help by the language server looks like this:

<img width="417" alt="screen shot 2017-02-05 at 6 31 39 pm" src="https://cloud.githubusercontent.com/assets/16890566/22632966/6927bf7c-ebd2-11e6-8801-734e13803b67.png">

where as it should look more like this

<img width="627" alt="screen shot 2017-02-05 at 6 38 44 pm" src="https://cloud.githubusercontent.com/assets/16890566/22632972/7239297a-ebd2-11e6-8bad-4fde5e897110.png">

**Comment by keegancsmith** [comment]
Hi @ramya-rao-a sorry for not responding sooner. I will look into this before the end of the week. It should be pretty easy to re-use the code we have in hover.go if you want to take a stab :)

**Comment by ramya-rao-a** [comment]
@keegancsmith I did give it a try (PR #137), but it only works for functions from the same package. Need help debugging why the logic doesn't work for functions from standard or other packages

**Comment by ramya-rao-a** [comment]
Updated the PR to make it work for functions from other package as well.
