### ISSUE TITLE
Enforce LSP ordering semantics

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/go-langserver#155]
LSP requires an ordering on how the server handles requests:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#request-notification-and-response-ordering

If a client sends LSPs request in rapid succession (e.g. textDocument/didOpen, textDocument/didChange, textDocument/didClose), the server MUST handle these events in the order they are received.

JSON RPC does not have any ordering requirements so JSON RPC libraries are not required to provide these ordering semantics.

For example, if each notification handler spawns a new goroutine, there is no guarantee of the order that requests will be handled.

The Go language server needs to implement these ordering semantics.

**Comment by keegancsmith** [comment]
FYI this change goes a long way to prevent this issue rearing its ugly head #160 

However,  analysis requests shortly followed by mutations to the FS may return stale data. I don't foresee this being a major issue until we start doing integration with features that integrate tightly with the edit flow (completion, signature help, etc)
