### ISSUE TITLE
Last reference not sent via $/partialResult

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/go-langserver#157]
I am the streaming references experiment enabled locally and it seems like the last reference is never sent via $/partialResult.

For example, if I expect 4 references back, I will get 3 references from $/partialResult and the final response will return all 4 references. This happens even if I delay the final response by an arbitrary amount.

Given the streaming semantics we discussed, it should be possible to construct the entire result from all $/partialResults.

**Comment by keegancsmith** [comment]
I haven't investigated yet, but out of interest is the final reference you looking for the declaration?

**Comment by nicksnyder** [comment]
> is the final reference you looking for the declaration?

Yes, that appears to be the case.
