### ISSUE TITLE
Out of order results from workspace/xreferences

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/go-langserver#167]
workspace/xreferences sometimes sends a $/partialResult after the final result.

![screen shot 2017-02-28 at 7 41 18 pm](https://cloud.githubusercontent.com/assets/754768/23445116/ece65e68-fded-11e6-99cd-388231d84719.png)

**Comment by slimsag** [comment]
That's pretty interesting, given from what I can tell [it's only possible for us to return the final result prior to sending the last partial result](https://github.com/sourcegraph/go-langserver/blob/master/langserver/workspace_refs.go#L178-L181)

Maybe this has something to do with it being a Notify call, or somehow a synchronization issue with our jsonrpc layer. Hmm. @keegancsmith any thoughts what would cause this?

**Comment by nicksnyder** [comment]
If `Notify` dispatches to a goroutine, then it is racing with the return value.

**Comment by keegancsmith** [comment]
We have some tech debt related to ordering in this server as well as the proxies between the language server and the UI for sourcegraph.com. That would explain the out of ordering.

**Comment by keegancsmith** [comment]
This is an issue in our lsp-proxy, not go-langserver. go-langserver does in fact send the notification before the result (`conn.Notify` blocks until the message is written on the wire). I am closing this out in favour of the lsp-proxy issue we have https://github.com/sourcegraph/sourcegraph/issues/4594
