### ISSUE TITLE
High memory usage after running for awhile

### ISSUE THREAD

**Issue by neelance** [sourcegraph/go-langserver#177]
I just enabled the langserver and did a few hovers for testing. Then vscode was in the background. After a few minutes my machine almost died. Apparently the langserver went up to 5.6GB of memory usage. I only have 4GB of physical ram, so no wonder my machine had trouble.

I'd say that memory usage has to stay constantly below 100MB to be a viable alternative.

**Comment by Brisdo** [comment]
I had the same issue...

Was there a resolution?

**Comment by beyang** [comment]
@Brisdo being tracked here now: https://github.com/sourcegraph/go-langserver/issues/178
