### ISSUE TITLE
Find references on interface method should show implementations of that method

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/go-langserver#179]
If find references on an interface method like Writer.Write, I want to see function declarations of Write that conform to this interface.

https://sourcegraph.com/github.com/golang/go/-/blob/src/io/io.go#L91:2-91:7

Right now, it only returns reference results for the call sites of these methods.

**Comment by sqs** [comment]
Fixed by #252 (although they are shown separately from references)
