### ISSUE TITLE
Standard library symbol search is sometimes slow, unreliable

### ISSUE THREAD

**Issue by beyang** [sourcegraph/go-langserver#180]
Repro:
- Go to https://sourcegraph.com/github.com/golang/go
- Search for "#marshaljson"
- It seems to spin indefinitely
- The symbol I was looking for is https://sourcegraph.com/github.com/golang/go@63a72fd447abb8a07bee9166e87bfe27780492c3/-/blob/src/encoding/json/encode.go#L220:2-220:13

Update: It appears `definition` on that symbol is very slow. I get a "Loading..." that lasts for more than 10 seconds.

![image](https://cloud.githubusercontent.com/assets/1646931/24633405/309f16aa-187d-11e7-940a-1d284bd48609.png)

**Comment by lindaxie** [comment]
No longer an issue. Closing.

**Comment by cstrike** [comment]
I meet the same problem, how to solve it?
