### ISSUE TITLE
textDocument /documentSymbol is missing receiver functions 

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#199]
_From @josh-tepper on August 11, 2017 17:39_

When I set `"go.useLanguageServer": true`, I no longer see receiver functions (aka methods) when I type "@" in the command palette (though I see all other symbols).  This is in contrast to the behavior when I use go.docsTool set to either godoc or gogetdoc.  Nonetheless, I wish that I had these symbols because they're useful!

_Copied from original issue: Microsoft/vscode-go#1140_

**Comment by ramya-rao-a** [comment]
_From @josh-tepper on August 25, 2017 14:44_

@ramya-rao-a have you seen this?  Should I file this with the sourcegraph folks or is this an artifact of the way vscode-go invokes or uses go-langserver?

I just updated my langserver with go get, and I have this version:
```
$ go-langserver -version
v2-dev
```

**Comment by ramya-rao-a** [comment]
Hey @josh-tepper 

Sorry my notifications are all in a mess, don't know how I missed this issue.

Yes, this should be logged in the repo for the language server.

No worries I'll move it.

**Comment by ramya-rao-a** [comment]
cc @slimsag

**Comment by josh-tepper** [comment]
@slimsag  -- I just wanted to check -- did you see this issue?  No rush, of course!

**Comment by slimsag** [comment]
Sorry for the (sever) delay in responding to this :) I haven't had a chance to look at/into this issue. @keegancsmith is going to take a look soon

**Comment by keegancsmith** [comment]
Hey @josh-tepper can you give more information on how to reproduce? When I try this myself I see methods.

**Comment by josh-tepper** [comment]
That's interesting.  I've just recently noticed that very occasionally, I do see methods, but mostly I still don't.

I'll turn on the option to cause vscode to invoke go-langserver with -trace, and I'll send details shortly (Monday).

**Comment by josh-tepper** [comment]
I'm not really sure how to explain how to reproduce.  I have a sizeable go project.  Here is a sample trace, but unfortunately I've had to redact it as this is all internal source code.  I'm not sure how useful this is:
> --> request #3: textDocument/documentSymbol: {"textDocument":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go"}}
<-- result #3: textDocument/documentSymbol: [{"name":"redactedConst1","kind":14,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":21,"character":0},"end":{"line":22,"character":6}}}},{"name":"redactedVar1","kind":13,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":25,"character":0},"end":{"line":25,"character":7}}}},{"name":"redactedFun1","kind":12,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":146,"character":5},"end":{"line":146,"character":20}}}},{"name":"redactedFun2","kind":12,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":90,"character":5},"end":{"line":90,"character":23}}}},{"name":"redactedFun3","kind":12,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":115,"character":5},"end":{"line":115,"character":28}}}},{"name":"redactedFun4","kind":12,"location":{"uri":"file:///Users/joshtepper/REDACTED/go/src/REDACTED.go","range":{"start":{"line":78,"character":5},"end":{"line":78,"character":29}}}}]

**Comment by josh-tepper** [comment]
What steps can I take to help.  I would say that the receiver functions are almost always excluded.

**Comment by josh-tepper** [comment]
Oh -- I actually think that I figured it out:
It seems to happen if and only if the type from the receiver is defined outside the current file (but per the requirements of the language, in the same package of course).

**Comment by keegancsmith** [comment]
@josh-tepper thanks, I just pushed a failing test case for that https://github.com/sourcegraph/go-langserver/pull/204 Will potentially work on a fix soon.

**Comment by josh-tepper** [comment]
Nice!  Will re-enable the sourcegraph language server and give it a try :-) @keegancsmith
