### ISSUE TITLE
Question: can we do any better on providing start and end ranges for loader errors?

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#20]
I'm building a Sublime Text plugin to work with the Go langserver, and a feature I'd like is to underline the error causing symbols when you have some code that is broken.

In app.go in sourcegraph/sourcegraph, I added "aaa" to the end of the http.Handler return argument for the first method.

The langserver returned the following (not the same start and end):
```
{"method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go","diagnostics":[{"range":{"start":{"line":25,"character":34},"end":{"line":25,"character":34}},"severity":1,"source":"go","message":"Handleraa not declared by package http"}]},"jsonrpc":"2.0"}
```

The errors are getting created here:
https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/diagnostics.go#L56-61

And you can see that we are purposefully setting start and end the same.

Maybe this is a limitation of whatever tool is creating the errors to begin with, I added some logging, and the full error text is:
```
/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go:26:35: Handleraa not declared by package http
```

Not urgent at all (the workaround is just to underline the token, in his case that would get us to underline "http," not "http.Handleraaa," but close enough). Was just wondering if there was some obvious verbosity setting we could pass whatever generated the error, and we could get end line number too.

**Comment by keegancsmith** [comment]
Man sourcegraph is pretty epic, I got an answer for you by just using our features from that link :D

So it seems the only place that generates errors from typechecking is here https://sourcegraph.com/github.com/golang/go@go1.7.1/-/blob/src/go/types/errors.go#L74

That seems to only send `error`'s with this type https://sourcegraph.com/github.com/golang/go@go1.7.1/-/blob/src/go/types/api.go#L41:6 which includes an FSet and Pos, so we can probably go backwards to a node to get a range :) I'll see how easy that is to do.
