### ISSUE TITLE
textDocument/hover response range is the position of the declaration

### ISSUE THREAD

**Issue by ckaznocha** [sourcegraph/go-langserver#200]
Hi,
Thanks for building go-langserver, I'm psyched for a go LSP. Yesterday evening I started a package for the new `atom-languageclient`. `atom-languageclient`'s Datatip expects the `range` in a hover response to be the location where the symbol is used however `go-langserver` returns the location where the symbol is declared. I'm not sure which is correct and the LSP spec is a bit ambiguous: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover

I've managed to work around it to get Atom's Datatips functioning but its a bit of a hack. If you're confident the current behavior is correct I'll open an issue for `atom-languageclient`.

**Comment by keegancsmith** [comment]
Thanks! I think you are right, we should be highlighting the current token for hover. The language is a bit ambigious, but it makes sense to be the document you can see, rather than potentially another file.

```
	/**
	 * An optional range is a range inside a text document
	 * that is used to visualize a hover, e.g. by changing the background color.
	 */
```

What do you think @slimsag @sqs?

**Comment by sqs** [comment]
Yes, that is correct. I believe VS Code would be ignoring the hover range if it’s not on the same line as the user’s cursor and instead supplying a default, which is why we didn’t see this issue before.

**Comment by keegancsmith** [comment]
Sorry about forgetting about this issue. I took a look today and the issue seems to be a regression from us switching to godef, our previous implementation did this correctly and our regression suite doesn't check hover range. So thanks for the report! I got started on updating our tests to catch this but ended up going down a massive rabbit hole. Will take a look again soon.
