### ISSUE TITLE
CompletionItem.TextEdit should be a pointer

### ISSUE THREAD

**Issue by Timmmm** [sourcegraph/go-langserver#215]
The current definition is:

```
type CompletionItem struct {
...
	TextEdit      TextEdit   `json:"textEdit,omitempty"`
...
}
```

It should be:

```
type CompletionItem struct {
...
	TextEdit      *TextEdit   `json:"textEdit,omitempty"`
...
}
```

Otherwise you *have* to provide an edit. The default `TextEdit` causes VSCode to log errors and doesn't show the completions.

Great package by the way, thanks!

**Comment by keegancsmith** [comment]
Thanks. I'll gladly accept a PR here, you've basically done it already in the issue description!

**Comment by Timmmm** [comment]
Yeah the only reason I didn't do it as a pull request is I wasn't sure if
anything else depends on it being a value type... If not then I'll send one!

**Comment by keegancsmith** [comment]
Thanks please do!
