### ISSUE TITLE
Hover fails for methods on types

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#223]
Hovering on `b.Bye` in the below code in VS Code fails

```
package main

import (
	"fmt"
)

func main() {

	b := &Hello{
		a: 1,
	}

	fmt.Println(b.Bye())
}

type Hello struct {
	a int
}

func (h *Hello) Bye() int {
	return h.a
}
```

<img width="930" alt="screen shot 2018-01-07 at 5 53 16 pm" src="https://user-images.githubusercontent.com/16890566/34656789-addaa26a-f3d3-11e7-9959-d88cce0e8ce9.png">

**Comment by keegancsmith** [comment]
Thanks, this looks easy to fix. Will add to the test suite.
