### ISSUE TITLE
not working properly with VS Code and Go Extension 

### ISSUE THREAD

**Issue by Macilias** [sourcegraph/go-langserver#228]
Hi, I use 
VS Code Version 1.19.2 (1.19.2) 
with Go Extension 0.6.73 
and Go version go1.9.2 darwin/amd64
running on macOS 10.13.2 (17C88) 

Yesterday I finally had the server running by deleting the otherwise recomended setting from VS Code: "go.useLanguageServer":true.
But today it refuses to work again, and also any combination fo the setting (true/false/not there) does not help any more.

Please help!

**Comment by Macilias** [comment]
update, it actually started to work again. The only difference is that there was one empty file without package declaration within the WS which prevented the compiler from building, once solved the find all option did work again. But really, it does not work with fully compiling code?
What is the best way to test the language server?

**Comment by keegancsmith** [comment]
Jump to definition and hover should work, some other features may trip up. When you say it wasn't working, what exactly do you mean? `"go.useLanguageServer": true` means it will use this project. Without that setting your issue may make more sense to file on https://github.com/Microsoft/vscode-go

**Comment by Macilias** [comment]
you are right, its a VS Code (or go extension) bug.
