### ISSUE TITLE
Publishing diagnostics more often

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#23]
Seen on the Sublime Text Go plugin: I noticed that diagnostics are only published when we see errors. The way that the TypeScript Sublime Plugin (Microsoft published) works is that there are empty diagnostic messages published on a given file for every keystroke.

As an example, ```{"method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go","diagnostics":[{"range":{"start":{"line":25,"character":34},"end":{"line":25,"character":34}},"severity":1,"source":"go","message":"Handlera not declared by package http"}]},"jsonrpc":"2.0"}Content-Length: 341
Content-Type: application/vscode-jsonrpc; charset=utf8```

Is published, but when I delete the "a" from Handlera, no diagnostic is published. This is caused by a couple issues:

The publish diagnostics method here does a range over diags:
https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/diagnostics.go#L17

And loader.go here, checks if the list is empty. It's probably an extra if check anyways, given what's in publish diagnostics:
https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/loader.go#L62-68

LSP is pretty vague on the issue:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#publishdiagnostics-notification

I'm open to doing this any old way. The two use cases are:
1. As I'm typing away in a file, and I make an error, I want to highlight the error. When it's fixed, I want the highlighting to go away.
2. There is a "Workspace Errors" function that the TypeScript Sublime plugin has, that somehow gets the Microsoft TypeScript LSP to cough up  a diagnostic for every file, and assembles a list. Here is the output from the terminal:
```{'body': {'diagnostics': [], 'file': '/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/node_modules/@types/mocha/index.d.ts'}, 'event': 'syntaxDiag', 'type': 'event', 'seq': 0}
{'body': {'diagnostics': [], 'file': '/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/node_modules/@types/mocha/index.d.ts'}, 'event': 'semanticDiag', 'type': 'event', 'seq': 0}
{'body': {'diagnostics': [], 'file': '/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/node_modules/@types/lodash/index.d.ts'}, 'event': 'syntaxDiag', 'type': 'event', 'seq': 0}
{'body': {'diagnostics': [], 'file': '/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/node_modules/@types/lodash/index.d.ts'}, 'event': 'semanticDiag', 'type': 'event', 'seq': 0}
```

and here is an example errror list (the end state):
```/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/web_modules/sourcegraph/repo/RepoStore.tsx [1 errors]
    (97, 74) Argument of type 'any' is not assignable to parameter of type 'never'.
/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/web_modules/sourcegraph/dashboard/DashboardContainer.tsx [2 errors]
    (9, 4) JSX element type 'OnboardingContainer' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'OnboardingContainer'.
    (9, 4) JSX element class does not support attributes because it does not have a 'props' property
/Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/ui/web_modules/sourcegraph/dashboard/OnboardingContainer.tsx [14 errors]
    (26, 42) Cannot find name 'asdfasdfContainer'.
    (37, 27) Cannot find name 'prevStasdfadsfate'.
    (53, 12) Property 'props' does not exist on type 'OnboardingContainer'.
    (55, 38) Property 'props' does not exist on type 'OnboardingContainer'.
    (56, 19) Property 'props' does not exist on type 'OnboardingContainer'.
    (58, 38) Property 'props' does not exist on type 'OnboardingContainer'.
    (65, 32) Property 'props' does not exist on type 'OnboardingContainer'.
    (78, 41) Property 'props' does not exist on type 'OnboardingContainer'.
    (79, 9) Property 'context' does not exist on type 'OnboardingContainer'.
    (83, 12) Property 'props' does not exist on type 'OnboardingContainer'.
    (84, 98) Property 'props' does not exist on type 'OnboardingContainer'.
    (87, 12) Property 'props' does not exist on type 'OnboardingContainer'.
    (88, 152) Property 'props' does not exist on type 'OnboardingContainer'.
    (91, 36) Property 'props' does not exist on type 'OnboardingContainer'.```

**Comment by keegancsmith** [comment]
We can certainly publish empty diagnostics. Any idea on the LSP call made for all the diagnostics? Couldn't find anything in the spec.

**Comment by sqs** [comment]
It's publishDiagnostics and it's sent by the server, not client.

**Comment by keegancsmith** [comment]
> It's publishDiagnostics and it's sent by the server, not client.

@sqs I was referring to @uforic's mention of:

> There is a "Workspace Errors" function that the TypeScript Sublime plugin has, that somehow gets the Microsoft TypeScript LSP to cough up a diagnostic for every file, and assembles a list.

**Comment by keegancsmith** [comment]
I think there are quite a few issues to clear up around caching/re-triggering typechecking on file changes. I won't be able to look into them this week more than likely, so just gonna un-assign myself for now. If this is an issue, lets chat about it :)

**Comment by keegancsmith** [comment]
@uforic what is the priority on this? Is this something covered by some of the new work by @alexsaveliev?

**Comment by uforic** [comment]
Low priority - I'm going to close this out for now. Thx for reminding me!

**Comment by ramya-rao-a** [comment]
I was testing the language server integration with VS Code, we can see the same thing and I'd like to re-open this issue.

If this is not a priority at the moment, can the publishing of diagnostics be disabled until this is fixed?
It gets pretty annoying when the error squigglies do not go away when the user has fixed the issue.

**Comment by slimsag** [comment]
Reopening per @ramya-rao-a 's comment just so this doesn't get missed! (I don't have context here so deferring to @keegancsmith )

**Comment by felixfbecker** [comment]
Just to clear up the semantics, any publishDiagnostics call overrides the current list of diagnostics. So if there were diagnostics and now there are none, the LS needs to send an empty array.

**Comment by keegancsmith** [comment]
@ramya-rao-a PR #128 should hopefully solve this issue.

**Comment by keegancsmith** [comment]
On further thought my PR did not fix the problem. It will be a bit of work to fix, so I have disabled publishDiagnostics in #131

**Comment by ramya-rao-a** [comment]
Thanks @keegancsmith!
