### ISSUE TITLE
Incorrect package naming in package: go-langserver\langserver\util

### ISSUE THREAD

**Issue by jmarais** [sourcegraph/go-langserver#232]
On a windows host with go1.9 I get the following error:
> go install github.com\sourcegraph\go-langserver
src\github.com\sourcegraph\go-langserver\langserver\internal\tools\buildutil.go:11:2: found packages util (context.go) and utils (os_windows.go) in \src\github.com\sourcegraph\go-langserver\langserver\util

I think the naming of the os_windows.go package should change from "utils" to "util".

I did that to fix the install process.

**Comment by keegancsmith** [comment]
Sorry about that! Fixed in master. I've turned on notifications from appveyor to avoid this in the future.
