### ISSUE TITLE
Find All References not working when using the language server in VS Code

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#240]
Am very sure this worked before, but with the latest bits for the language server, the `Find All References` feature is not working

<img width="1033" alt="screen shot 2018-02-22 at 10 48 45 am" src="https://user-images.githubusercontent.com/16890566/36557754-033912b0-17be-11e8-97cc-c0906020cbbf.png">

**Comment by keegancsmith** [comment]
@ramya-rao-a can you try again, I believe this PR fixes the issue https://github.com/sourcegraph/go-langserver/pull/230

**Comment by ramya-rao-a** [comment]
Works now
