### ISSUE TITLE
No difference between interfaces and classes

### ISSUE THREAD

**Issue by vitreuz** [sourcegraph/go-langserver#241]
Hi, this probably ends up being more of a feature request than anything else. But I noticed adding an interface type to the [test here](https://github.com/sourcegraph/go-langserver/blob/1e571d690e259cdb944b96c5d3596dff9e6cb13d/langserver/langserver_test.go#L779) (such as `type UVW interface{}`) returns it as type class (specifically `"/src/test/pkg/abc.go:class:UVW:3:6"`). 

Since the lsp has a value for [interfaces](https://github.com/sourcegraph/go-langserver/blob/1e571d690e259cdb944b96c5d3596dff9e6cb13d/pkg/lsp/service.go#L401) I'd expect this to return an interface type. Specifically, this seems to lump structs and interfaces into the same category on downstream clients (e.g. Symbol lookup in vscode).

**Comment by keegancsmith** [comment]
This actually shouldn't be too hard to add so is likely a good candidate for a first time contribution. @slimsag are there any implications in our cross-referencing stack if workspace/symbols (or its shared code) starts to treat interfaces as interfaces in LSP instead of classes?
