### ISSUE TITLE
initial go get attempt fails

### ISSUE THREAD

**Issue by mrwonko** [sourcegraph/go-langserver#245]
My initial attempt to `go get -u github.com/sourcegraph/go-langserver` failed with an

> unexpected directory layout

error, which according to golang/go#21057 could be related to use of symlinks. (On second try it worked.) The vendored `github.com/prometheus/procfs` version contains symlinks, which have since been removed. I suggest vendoring a newer version, that should probably fix the issue.

**Comment by keegancsmith** [comment]
Thanks. I'll take a look.

**Comment by keegancsmith** [comment]
Should be fixed by https://github.com/sourcegraph/go-langserver/commit/911b6e29dd9f76ddd37a5acaa7fb429f6ade2927
