### ISSUE TITLE
Definition range

### ISSUE THREAD

**Issue by nicot** [sourcegraph/go-langserver#25]
Definition range should span the entire function body and declaration. The Go AST position info for the def only has the position of the name in it, so we'd have to dig a little deeper to get this to work right.

Start here: https://github.com/sourcegraph/go-langserver/blob/master/langserver/definition.go#L29. These lines can be removed once the entire function body is included: https://github.com/sourcegraph/go-langserver/blob/master/langserver/definition.go#L44-L48.

**Comment by keegancsmith** [comment]
@uforic should this be part of the editor extension project https://github.com/sourcegraph/go-langserver/projects/1

**Comment by uforic** [comment]
Cool - @nicot , mind talking about the use case? Couldn't tell from the LSP protocol.md if this was desired behavior, just `definition location of a symbol`, which seems more like just the name.

Maybe the entire range could be an additional field in the resolvedSymbol request? : https://github.com/sourcegraph/language-server-protocol/pull/2

**Comment by nicot** [comment]
This is the way that VSCode expects it to work, so that we can show declarations in the hover tooltip. This is the way that most language servers work, so it should not be an extension.

**Comment by uforic** [comment]
Cool - makes sense. Let's submit a PR to the LSP folks to this affect, the language on the protocol is kinda vague.

@nicot , can you link to the code where they expect the range to encompass the whole function? Will help with the PR.

**Comment by nicot** [comment]
This is the gotoDeclaration command that the hover uses to provide a preview: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L329.

**Comment by slimsag** [comment]
> Cool - makes sense. Let's submit a PR to the LSP folks to this affect, the language on the protocol is kinda vague.

@uforic I'm all for clarification of docs :D but tbh I think it's already straightforward:

1. `textDocument/definition` returns a `Location`: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#location
 
2. `Location` is defined as:

```
interface Location {
    uri: string;
    range: Range;
}
```

And to quote the `Range` docs:

> #### Range
> 
> A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore the end position is exclusive.
> 
> ```typescript
> interface Range {
> 	/**
> 	 * The range's start position.
> 	 */
> 	start: Position;
> 
> 	/**
> 	 * The range's end position.
> 	 */
> 	end: Position;
> }
> ```

For me, I can't see any other use of declaring a `Range` instead of just a `Position`: the only possibility is to describe the range start/end positions of the symbol in question. 

Just providing my view of the docs, but if you have suggestions to improve them I'm all for it :D

**Comment by slimsag** [comment]
FYI also having the full range would be useful for def landing, too.

**Comment by sqs** [comment]
Having the full range is also useful for impact analysis :smile:

**Comment by uforic** [comment]
Roger - the interpretation I wrongly had is that the range was the token in question, so that an editor could highlight it in the event of jump to (I haven't seen jump to's that highlight the whole fn, just ones that highlight the token in question), but given that VSCode does it and y'all know about it, I guess it was just me that was confused! Party.

**Comment by nicot** [comment]
I'm suggesting a change in the contents of the range returned by textDocument/definition. There are two things we could return for a definition request on https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go#L39:6.

One spanning just the identifier: `Router`

Another spanning the entire body:

```
type Router struct {
	// Configurable Handler to be used when no route matches.
	NotFoundHandler http.Handler
	// Parent route, if this is a subrouter.
	parent parentRoute
	// Routes to be matched, in order.
	routes []*Route
	// Routes by name for URL building.
	namedRoutes map[string]*Route
	// See Router.StrictSlash(). This defines the flag for new routes.
	strictSlash bool
	// See Router.SkipClean(). This defines the flag for new routes.
	skipClean bool
	// If true, do not clear the request context after handling the request.
	// This has no effect when go1.7+ is used, since the context is stored
	// on the request itself.
	KeepContext bool
	// see Router.UseEncodedPath(). This defines a flag for all routes.
	useEncodedPath bool
}
```

I'm arguing that the second is better. The language protocol documentation does not provide guidance here, but in practice the body is more useful. It is also what most tools expect and provide.

**Comment by slimsag** [comment]
I've always interpreted the spec to mean include the entire body, as you're suggesting @nicot. I think we should go with that.

I agree the spec could be more clear here @uforic -- I hadn't considered just spanning the name (which is a very real possibility). A PR here as you suggested earlier would be awesome!

**Comment by keegancsmith** [comment]
@uforic what is the priority on this? Is this something covered by some of the new work by @alexsaveliev?

**Comment by keegancsmith** [comment]
@lindaxie, @mejamiewilson Is this something we would like soon?

**Comment by felixfbecker** [comment]
I don't think this is even desirable. The range that is returned by definition should be the exact range you can invoke find-all-refs on, just like the range for a reference should be the exact range you can invoke j2d on. If you include the whole declaration body vs just the name, that is not true.

**Comment by nicot** [comment]
Yeah I've actually done a 180 on this issue and think it should just be the name. There's a bug with the TypeScript langserver where it has the entire declaration behavior, and it breaks J2d on internal class references and recursive calls.

**Comment by keegancsmith** [comment]
Ok, then I believe lets just close it out. Thanks!
