### ISSUE TITLE
Go Lang Server not installing properly

### ISSUE THREAD

**Issue by swidnikk** [sourcegraph/go-langserver#256]
package github.com/sourcegraph/go-langserver
	imports context: unrecognized import path "context"

This is what I get—help!

go get -u github.com/sourcegraph/go-langserver
package github.com/sourcegraph/go-langserver
	imports context: unrecognized import path "context"
failed MSpanList_Insert 0x767588 0x6ed15f804042 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x6a3730, 0x767588)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x6a36c0, 0x2, 0x10000000024, 0x791d9)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x6ac878, 0x3d7da0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x74e000, 0x24, 0x800764d70)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:198 fp=0xc2083505c8 sp=0xc2083505c0
runtime.mallocgc(0x680, 0x0, 0x3, 0xc208317900)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:178 +0x849 fp=0xc208350678 sp=0xc2083505c8
runtime.rawmem(0x680, 0x680)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:371 +0x39 fp=0xc2083506a0 sp=0xc208350678
runtime.growslice(0x340000, 0xc208317900, 0x500, 0x500, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/slice.go:83 +0x237 fp=0xc208350700 sp=0xc2083506a0
go/build.(*importReader).readByte(0xc2082c6f00, 0x41)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:43 +0xd3 fp=0xc208350790 sp=0xc208350700
go/build.(*importReader).peekByte(0xc2082c6f00, 0x42f801, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:89 +0x164 fp=0xc2083507d0 sp=0xc208350790
go/build.(*importReader).readKeyword(0xc2082c6f00, 0x47db90, 0x7)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:122 +0x2d fp=0xc2083507f8 sp=0xc2083507d0
go/build.readImports(0x7606d0, 0xc20804eb30, 0xc20804eb00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/read.go:207 +0xe7 fp=0xc208350850 sp=0xc2083507f8
go/build.(*Context).matchFile(0x693820, 0xc2082571c0, 0x3d, 0xc20832e53e, 0xe, 0xc20831a901, 0xc2082c93e0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/build.go:958 +0x5be fp=0xc208350998 sp=0xc208350850
go/build.(*Context).Import(0x693820, 0xc208267681, 0x20, 0x7fff5fbffccf, 0x18, 0x4, 0x186, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/go/build/build.go:624 +0x1d10 fp=0xc208351288 sp=0xc208350998
main.loadImport(0xc208267681, 0x20, 0x7fff5fbffccf, 0x18, 0xc20801fe40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:267 +0x4d9 fp=0xc208351440 sp=0xc208351288
main.loadPackage(0xc208267681, 0x20, 0xc20801fe40, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/pkg.go:867 +0xf7c fp=0xc208351680 sp=0xc208351440
main.download(0xc208267681, 0x20, 0xc20801fe40, 0xc2082c5c00)
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/get.go:212 +0x15b7 fp=0xc208351980 sp=0xc208351680
main.download(0x7fff5fbff7ba, 0x24, 0xc20801fe40, 0xc20808da00)
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/get.go:245 +0x916 fp=0xc208351c80 sp=0xc208351980
main.runGet(0x68ed60, 0xc20800a030, 0x1, 0x1)
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/get.go:79 +0x16d fp=0xc208351d98 sp=0xc208351c80
main.main()
	/usr/local/Cellar/go/1.4.2/libexec/src/cmd/go/main.go:163 +0x608 fp=0xc208351f98 sp=0xc208351d98
runtime.main()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:63 +0xf3 fp=0xc208351fe0 sp=0xc208351f98
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208351fe8 sp=0xc208351fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35
swid-mba:genblue swid$

**Comment by Contextualist** [comment]
You are using a Go distribution that is too old (1.4.2), and it may not have the built-in package `context`. I recommend you to upgrade your Go and try again. Seem like you have installed Go via `homebrew`, so simply `brew update go` will do.

**Comment by swidnikk** [comment]
Many thanks! Just beginning with this language and hope to cross this hurdle soon. 

**$ which go**
/usr/local/bin/go

**$ go version**
go version go1.10.1 darwin/amd64

**$ cat ~/.bashrc | grep GO**
GOROOT=/usr/local/opt/go/libexec/bin
GOPATH=$HOME/code/genblue
GOBIN=$GOPATH/bin
PATH=$PATH:$GOBIN:$GOROOT

**$ brew upgrade go**
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
autopep8            fuse-emulator       gutenberg           s6

Error: go 1.10.1 already installed

**Comment by keegancsmith** [comment]
Does `go get -u github.com/sourcegraph/go-langserver` still not work, even with go1.10?

**Comment by swidnikk** [comment]
Thanks @keegancsmith and that's correct, see below. As @Contextualist mentioned it looks like the built in `context ` package is missing. Below is my path and the versions of go currently installed. This appears to be the latest release listed on [golang.org/dl](https://golang.org/dl/). 

**$ echo $PATH**
~/.nvm/versions/node/v8.9.4/bin:/usr/local/sbin:/usr/local/bin:/Library/Developer/CommandLineTools/usr/bin:~/bin:/usr/local/bin:~/bin/gam:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:~/code/genblue/bin:/usr/local/opt/go/libexec/bin:~/.rvm/bin

**$ /usr/local/opt/go/libexec/bin/go version**
go version go1.10.1 darwin/amd64

**$ /usr/local/go/bin/go version**
go version go1.10 darwin/amd64

**$ cd $GOHOME**
$ go get -u github.com/sourcegraph/go-langserver
package context: unrecognized import path "context" (import path does not begin with hostname)
package flag: unrecognized import path "flag" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package container/list: unrecognized import path "container/list" (import path does not begin with hostname)
package sync: unrecognized import path "sync" (import path does not begin with hostname)
package encoding/binary: unrecognized import path "encoding/binary" (import path does not begin with hostname)
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package encoding: unrecognized import path "encoding" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package log: unrecognized import path "log" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package sort: unrecognized import path "sort" (import path does not begin with hostname)
package strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package time: unrecognized import path "time" (import path does not begin with hostname)
package unicode/utf8: unrecognized import path "unicode/utf8" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package net/http: unrecognized import path "net/http" (import path does not begin with hostname)
package math/rand: unrecognized import path "math/rand" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package compress/gzip: unrecognized import path "compress/gzip" (import path does not begin with hostname)
package expvar: unrecognized import path "expvar" (import path does not begin with hostname)
package regexp: unrecognized import path "regexp" (import path does not begin with hostname)
package mime: unrecognized import path "mime" (import path does not begin with hostname)
package encoding/hex: unrecognized import path "encoding/hex" (import path does not begin with hostname)
package io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package net: unrecognized import path "net" (import path does not begin with hostname)
package path: unrecognized import path "path" (import path does not begin with hostname)
package runtime/debug: unrecognized import path "runtime/debug" (import path does not begin with hostname)
package sync/atomic: unrecognized import path "sync/atomic" (import path does not begin with hostname)
package go/ast: unrecognized import path "go/ast" (import path does not begin with hostname)
package go/token: unrecognized import path "go/token" (import path does not begin with hostname)
package text/template: unrecognized import path "text/template" (import path does not begin with hostname)
package unicode: unrecognized import path "unicode" (import path does not begin with hostname)
package path/filepath: unrecognized import path "path/filepath" (import path does not begin with hostname)
package go/build: unrecognized import path "go/build" (import path does not begin with hostname)
package go/parser: unrecognized import path "go/parser" (import path does not begin with hostname)
package go/scanner: unrecognized import path "go/scanner" (import path does not begin with hostname)
package net/rpc: unrecognized import path "net/rpc" (import path does not begin with hostname)
package os/exec: unrecognized import path "os/exec" (import path does not begin with hostname)
package text/scanner: unrecognized import path "text/scanner" (import path does not begin with hostname)
package go/printer: unrecognized import path "go/printer" (import path does not begin with hostname)
package go/types: unrecognized import path "go/types" (import path does not begin with hostname)
package net/url: unrecognized import path "net/url" (import path does not begin with hostname)
package go/format: unrecognized import path "go/format" (import path does not begin with hostname)
package net/http/pprof: unrecognized import path "net/http/pprof" (import path does not begin with hostname)

**Comment by keegancsmith** [comment]
Can you just include the output of these three commands:

```
go version
go env
go get github.com/sourcegraph/go-langserver
```

**Comment by swidnikk** [comment]
@keegancsmith here you are

**$ go version**
go version go1.10.1 darwin/amd64

**$ go env**
GOARCH="amd64"
GOBIN="/Users/swid/code/genblue/bin"
GOCACHE="/Users/swid/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/swid/code/genblue"
GORACE=""
GOROOT="/usr/local/opt/go/libexec/bin"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/bin/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/bin/gcc-4.2"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8_/l9shhyl16897whkqx63pfzmr0000gp/T/go-build462152716=/tmp/go-build -gno-record-gcc-switches -fno-common"

**$ go get github.com/sourcegraph/go-langserver**
package context: unrecognized import path "context" (import path does not begin with hostname)
package flag: unrecognized import path "flag" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
package errors: unrecognized import path "errors" (import path does not begin with hostname)
package container/list: unrecognized import path "container/list" (import path does not begin with hostname)
package sync: unrecognized import path "sync" (import path does not begin with hostname)
package encoding/binary: unrecognized import path "encoding/binary" (import path does not begin with hostname)
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package encoding: unrecognized import path "encoding" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)
package log: unrecognized import path "log" (import path does not begin with hostname)
package math: unrecognized import path "math" (import path does not begin with hostname)
package os: unrecognized import path "os" (import path does not begin with hostname)
package reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package sort: unrecognized import path "sort" (import path does not begin with hostname)
package strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package strings: unrecognized import path "strings" (import path does not begin with hostname)
package time: unrecognized import path "time" (import path does not begin with hostname)
package unicode/utf8: unrecognized import path "unicode/utf8" (import path does not begin with hostname)
package unsafe: unrecognized import path "unsafe" (import path does not begin with hostname)
package net/http: unrecognized import path "net/http" (import path does not begin with hostname)
package math/rand: unrecognized import path "math/rand" (import path does not begin with hostname)
package runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package compress/gzip: unrecognized import path "compress/gzip" (import path does not begin with hostname)
package expvar: unrecognized import path "expvar" (import path does not begin with hostname)
package regexp: unrecognized import path "regexp" (import path does not begin with hostname)
package mime: unrecognized import path "mime" (import path does not begin with hostname)
package encoding/hex: unrecognized import path "encoding/hex" (import path does not begin with hostname)
package io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package net: unrecognized import path "net" (import path does not begin with hostname)
package path: unrecognized import path "path" (import path does not begin with hostname)
package runtime/debug: unrecognized import path "runtime/debug" (import path does not begin with hostname)
package sync/atomic: unrecognized import path "sync/atomic" (import path does not begin with hostname)
package go/ast: unrecognized import path "go/ast" (import path does not begin with hostname)
package go/token: unrecognized import path "go/token" (import path does not begin with hostname)
package text/template: unrecognized import path "text/template" (import path does not begin with hostname)
package unicode: unrecognized import path "unicode" (import path does not begin with hostname)
package path/filepath: unrecognized import path "path/filepath" (import path does not begin with hostname)
package go/build: unrecognized import path "go/build" (import path does not begin with hostname)
package go/parser: unrecognized import path "go/parser" (import path does not begin with hostname)
package go/scanner: unrecognized import path "go/scanner" (import path does not begin with hostname)
package net/rpc: unrecognized import path "net/rpc" (import path does not begin with hostname)
package os/exec: unrecognized import path "os/exec" (import path does not begin with hostname)
package text/scanner: unrecognized import path "text/scanner" (import path does not begin with hostname)
package go/printer: unrecognized import path "go/printer" (import path does not begin with hostname)
package go/types: unrecognized import path "go/types" (import path does not begin with hostname)
package net/url: unrecognized import path "net/url" (import path does not begin with hostname)
package go/format: unrecognized import path "go/format" (import path does not begin with hostname)
package net/http/pprof: unrecognized import path "net/http/pprof" (import path does not begin with hostname)

**Comment by slimsag** [comment]
@swidnikk You are overwriting the `GOROOT` that is already set for you by homebrew:

```
$ cat ~/.bashrc | grep GO
GOROOT=/usr/local/opt/go/libexec/bin
GOPATH=$HOME/code/genblue
GOBIN=$GOPATH/bin
PATH=$PATH:$GOBIN:$GOROOT
```

Get rid of the `GOROOT=...` line and it should work fine.

**Comment by swidnikk** [comment]
@slimsag thank you! That brings me a step closer I believe. I get the following error now, which I am working on next. Apparently I have 4.1, might need an xcode update

**$ go get github.com/sourcegraph/go-langserver**
# runtime/cgo
fork/exec /usr/bin/gcc-4.2: no such file or directory

**Comment by slimsag** [comment]
Glad to hear that fixed the issue :)
