### ISSUE TITLE
Discussion: Should we include an example line in addition to a Location as a return value for workspace/references

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#26]
https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/pkg/lsp/structures.go#L27-30

Can we return an `ExtendedLocation` here, that includes the containing line in the file? 

Reasons to do this:
Any UI for references usually requires a sample line, reasonable assumption to make
The TS server bundled with the MSoft Sublime plugin does this
Without it, we have to look up every file and fine references on the editor plugin side, when it seems like the language server has already done this work and might as well include the information.

Reasons not to do this:
Breaking change from LSP
Other LSP's won't do this as a result, meaning that our Sublime Connector won't work with LSP's.

Perhaps this is a change worth suggesting to the LSP folks? @sqs , what are your thoughts on this?

**Comment by keegancsmith** [comment]
@uforic do you still think this is a good idea? Somewhat easy to implement, so we can propose it upstream.

**Comment by uforic** [comment]
Yo! I proposed this in the LSP spec, and they put it in the LSP 3.0 milestone. Let's wait to implement until that's published, closing for now!

**Comment by keegancsmith** [comment]
Awesome! Link?

**Comment by uforic** [comment]
Right on: https://github.com/Microsoft/language-server-protocol/pull/121
