### ISSUE TITLE
`failed to find doc object for` should not be returned

### ISSUE THREAD

**Issue by kdarkhan** [sourcegraph/go-langserver#261]
Due to [this line](https://github.com/sourcegraph/go-langserver/blob/b398c472184b78ac6e8e6997addd08f72a8ce2cc/langserver/hover.go#L336) langserver returns an error `failed to find doc object for ...` whenever no documentation is found for a token and it happens often. I am using [emacs-lsp](https://github.com/emacs-lsp/lsp-mode) and it renders such errors in `Messages` buffer and at the status bar. I believe such errors should not be returned because there are many cases when a token has no documentation.

**Comment by keegancsmith** [comment]
yup, the LSP spec in fact indicates as much. thanks for the report, will fix.

**Comment by keegancsmith** [comment]
@kdarkhan it doesn't happen whenever there is no documentation, only when our ast inspector fails to find the relevant node. Do you have a reproduction on some OSS go code, so I can try reproduce?

**Comment by kdarkhan** [comment]
Here is an example using https://github.com/cortesi/devd/blob/master/server.go#L283
The errors are shown at the bottom status bar, and whenever hover succeeds, it is shown at the top.
![output](https://user-images.githubusercontent.com/1087493/39166451-976bbd58-47ab-11e8-85e9-e6d767dc6517.gif)

**Comment by slimsag** [comment]
@kdarkhan I've just merged @keegancsmith's PR https://github.com/sourcegraph/go-langserver/pull/263#pullrequestreview-114912922 so please give this another try and let us know if it works now :)

You can get the latest binary by running the same `go get` command in the REAMDE:

```bash
go get -u github.com/sourcegraph/go-langserver
```

**Comment by kdarkhan** [comment]
@slimsag @keegancsmith this works, thanks!

**Comment by ethanrubio** [comment]
@kdarkhan sorry to hijack this, but would you mind sharing your emacs config to a fellow emacs user? I'm trying to get lsp-go to work with little success and your emacs config looks great!

**Comment by kdarkhan** [comment]
@ethanrubio sure, [here](https://gist.github.com/kdarkhan/d8f337a3639c0abfeefa327ac94e2686) is my current setup.
I am using Spacemacs. The config above is not very clean but is working for go code. You will have to install the go tools manually.
