### ISSUE TITLE
value of scope is never used

### ISSUE THREAD

**Issue by heltonmarx** [sourcegraph/go-langserver#267]
The [staticcheck](https://staticcheck.io/) reports : 
` this value of scope is never used ` for `scope` variable [here](https://github.com/sourcegraph/go-langserver/blob/master/langserver/internal/gocode/decl.go#L891). 

Seems like this `scope` could be ignored:
```go
it, _ = advance_to_type(func_predicate, it, s)
```
Or substitute `s` on return on line [893](https://github.com/sourcegraph/go-langserver/blob/master/langserver/internal/gocode/decl.go#L893).

```go
return func_return_type(ct, index), scope, false
```

And a really small tip: 
This [else](https://github.com/sourcegraph/go-langserver/blob/master/langserver/internal/gocode/decl.go#L880) clause could be avoided.

I'm not sure If  this is the correct place to report or on https://github.com/nsf/gocode, considering this is not a real issue, just a warning report of staticcheck.

**Comment by keegancsmith** [comment]
Thanks. Yeah this is just a vendored in copy of gocode modified to be used as a lib. Upstream may appreciate the report. I'd also happily accept a PR.
