### ISSUE TITLE
Add goimports functionality to the DocumentFormatting

### ISSUE THREAD

**Issue by JeanMertz** [sourcegraph/go-langserver#272]
Not sure if this is something you'd consider, but it would be nice if it was possible to auto add missing imports.

I use this diff locally, which seems to do the trick, but I haven't tested this thoroughly yet:

```diff
diff --git a/langserver/format.go b/langserver/format.go
index 7678fc9..6ab56bd 100644
--- a/langserver/format.go
+++ b/langserver/format.go
@@ -4,13 +4,13 @@ import (
        "bytes"
        "context"
        "fmt"
-       "go/ast"
        "go/parser"
        "go/printer"
        "go/token"
        "path"
 
        "golang.org/x/tools/go/buildutil"
+       "golang.org/x/tools/imports"
 
        "github.com/sourcegraph/go-langserver/langserver/util"
        "github.com/sourcegraph/go-langserver/pkg/lsp"
@@ -33,8 +33,6 @@ func (h *LangHandler) handleTextDocumentFormatting(ctx context.Context, conn jso
                return nil, err
        }
 
-       ast.SortImports(fset, file)
-
        var buf bytes.Buffer
        cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
        err = cfg.Fprint(&buf, fset, file)
@@ -43,6 +41,12 @@ func (h *LangHandler) handleTextDocumentFormatting(ctx context.Context, conn jso
        }
 
        b := buf.Bytes()
+
+       b, err = imports.Process("", b, nil)
+       if err != nil {
+               return nil, err
+       }
+
        orig, err := h.readFile(ctx, params.TextDocument.URI)
        if err != nil {
                return nil, err
```

**Comment by keegancsmith** [comment]
I'm happy with changing our default to using goimports. If someone prefers plain old go fmt then we can provide an option later. Can you send a PR?

**Comment by lloiser** [comment]
#83 is probably also needed to get this working, right?

**Comment by JeanMertz** [comment]
Interesting @lloiser. I guess that answers the issue I posted here:

https://github.com/tomv564/LSP/issues/319

So yes, the above "works", but as explained in the above issue, it's not very user friendly (but the current `gofmt` isn't either, since it suffers from the same problem).

**Comment by maximbaz** [comment]
I think having goimports functionality is very useful. Since #83 is merged and you have the working patch, @JeanMertz would you please create the PR?

**Comment by otto-md** [comment]
It would be very nice if it was possible to also configure the [LocalPrefix](https://github.com/golang/tools/blob/059bec968c61383b574810040ba9410712de36c5/imports/fix.go#L35-L38) if this is implemented.
