### ISSUE TITLE
Reference "gogetdoc" as a dependency in the docs?

### ISSUE THREAD

**Issue by stouf** [sourcegraph/go-langserver#273]
After installing this language server implementation, I tried to use the hover feature and got an error telling me the command `gogetdoc` could not be found. I could not find any note about an option that would let me specify what command the hover function should use. I decided to install [gogetdoc](https://github.com/zmb3/gogetdoc) and the hover function started to work after that.

My questions are:

- Is there an option to specify which command the hover feature should be using?
- If [gogetdoc](https://github.com/zmb3/gogetdoc) is an actually dependency for the hover feature to work, shouldn't we write it down somewhere in the README?

**Comment by keegancsmith** [comment]
we don't shell out to gogetdoc (nor do we have any references to it in our repo), which means this is likely an issue in the client you are using (ie the extension to your editor) rather than go-langserver.

**Comment by stouf** [comment]
Thanks for the answer.
I currently have the following installed:

- [This language server implementation](https://github.com/sourcegraph/go-langserver/)
- [This language-server client](https://github.com/autozimu/LanguageClient-neovim)
- The [vim-go](https://github.com/fatih/vim-go) plugin [recommended by Golang](https://golang.org/doc/editors.html?h=vim) for Vim

`vim-go` and the language-server suite have big overlaps in terms of features and I was considering using only one or the other instead of using both in the same time but I am still using both for some reasons.
I could confirm the one calling `gogetdoc` is actually go-vim (https://github.com/fatih/vim-go/blob/e1002d8978e55c0762cc9e8f4de05d91a3e380d7/doc/vim-go.txt#L1302-L1308).

Thank you again for your answer.
