### ISSUE TITLE
doesn't compile with current go master

### ISSUE THREAD

**Issue by OneOfOne** [sourcegraph/go-langserver#276]
```
# github.com/sourcegraph/go-langserver/langserver/internal/godef/go/parser
../../sourcegraph/go-langserver/langserver/internal/godef/go/parser/parser.go:1213:46: too few values in &ast.CompositeLit literal
```

**Comment by keegancsmith** [comment]
Seems there is a new field `Incomplete`. https://sourcegraph.sgdev.org/github.com/golang/go@master/-/blob/src/go/ast/ast.go#L266:2 vs https://sourcegraph.sgdev.org/github.com/golang/go@go1.10/-/blob/src/go/ast/ast.go#L266:2

**Comment by OneOfOne** [comment]
What I did locally to get it to compile is simply using named fields, should be future-proof:

```
	return &ast.CompositeLit{
		Type:   typ,
		Lbrace: lbrace,
		Elts:   elts,
		Rbrace: rbrace,
	}
```
