### ISSUE TITLE
Signature Help returns "cannot import absolute path"

### ISSUE THREAD

**Issue by jussij** [sourcegraph/go-langserver#283]
I have a question about the _textDocument/signatureHelp_ method.

This test is running on Windows 10 and for the test I have a simple test.go file:

```

  Directory of D:\Go\src\github.com\jussij\Test
 
 27/05/2018  03:26 PM               284 test.go

```
On the machine the GOPATH environment variable is set to this:

```
D:\Go\src
```

I send the server the following message:

```
{
    "jsonrpc":"2.0",
    "id":2,
    "method":"textDocument/signatureHelp",
    "params":{
        "textDocument":{
            "uri":"file:///D:/Go/src/github.com/jussij/Test/test.go"},
        "position":{"line":18,"character":12}}
}
```

This results in the following error response:

```
{
    "id":2,
    "error":{
        "code":0,
        "message":"import \"/d:/go/src/github.com/jussij/test\": cannot import absolute path",
        "data":null},
    "jsonrpc":"2.0"
}
```

By comparison sending this _textDocument/completion_ request:

```
{
    "jsonrpc":"2.0",
    "id":3,
    "method":"textDocument/completion",
    "params":{
        "textDocument":{
            "uri":"file:///D:/Go/src/github.com/jussij/Test/test.go"},
        "position":{"line":18,"character":5},
        "context":{"triggerKind":2,"triggerCharacter":"."}}
}
```
Returns the expected completion data:
```
{
    "id":3,
    "result":{
        "isIncomplete":false,
        "items":[{"label":"Errorf",
                  "kind":3,
                  "detail":"func(format string, a ...interface{}) error",
                  ...
                  } }
}
```
So the signatureHelp fails but the completions (and find references) requests work.

Looking at the go-langserver code I see the request fails in the ContainingPackage function found in this file:

```
sourcegraph\go-langserver\langserver\build_context.go
```

In that file the ContainingPackage function finds a pkg but the XTestGoFiles call returns no files:

```
if pkg != nil {
	base := path.Base(filename)
	for _, f := range pkg.XTestGoFiles {
		if f == base {
			xtest = true
			break
		}
	}
```

Any ideas as to what might be going wrong?

Thanks in advance.

**Comment by keegancsmith** [comment]
we wrap gocode for completion, but signature helper we wrote ourselves which relies on the `go/*` packages. It looks like when we try and import the package that fails? It is hard for me to debug further since I do not have a windows machine. 

Do you mind sharing your `test.go` and any other go files in `D:/Go/src/github.com/jussij/Test`.

**Comment by jussij** [comment]
Please close this issue and put it down to a user error at my end :(
After some more investigation I found that while the GOPATH looked correct, it was not correct for the test file being used.
After fixing that GOPATH issue the signature features worked perfectly :)
Thanks and sorry for the false alarm.
