### ISSUE TITLE
Hover response doesn't always comply to spec

### ISSUE THREAD

**Issue by ul** [sourcegraph/go-langserver#284]
### Steps to reproduce

* go get -u github.com/sourcegraph/go-langserver
* git clone https://github.com/sourcegraph/go-langserver.git
* send to server:

```
{"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{},"workspace":{"applyEdit":null,"didChangeConfiguration":null,"didChangeWatchedFiles":null,"executeCommand":null,"symbol":null,"workspaceEdit":null}},"processId":83073,"rootPath":"/Users/ul/go-langserver","rootUri":"file:///Users/ul/go-langserver","trace":"off"},"id":0}
```

* wait for response
* send to server (actual `text` field content is omitted for brevity)

```
 {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"go","text":"...","uri":"file:///Users/ul/go-langserver/langserver/handler.go","version":1}}}
```

* send to server

```
{"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":27,"line":155},"textDocument":{"uri":"file:///Users/ul/go-langserver/langserver/handler.go"}}
```

(it's word `recover` on the line 156 of [handler.go](https://github.com/sourcegraph/go-langserver/blob/master/langserver/handler.go#L156)

### Expected behaviour

Server responds with either

```
 {"id":1,"result":null,"jsonrpc":"2.0"}
```

or

```
 {"id":1,"result":{"contents":[]},"jsonrpc":"2.0"}
```

### Actual behaviour

Server responds with

```
 {"id":1,"result":{"contents":null},"jsonrpc":"2.0"}
```

**Comment by keegancsmith** [comment]
I thought I fixed this recently, but must of been another language server since I can't find the commit. Will fix now.

**Comment by ul** [comment]
🎉 Thank you!
