### ISSUE TITLE
go-langserver: `invalid root path "file://": must be file:/// URI`

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#286]
_From @Dominik-K on February 9, 2018 12:31_

In a new VSCode (`1.21.0-insider`, d28f0960) window, I opened a simple Go file `/tmp/vscode-test.go` and get the following error message popup:

<img width="896" alt="screen shot 2018-02-09 at 13 24 19" src="https://user-images.githubusercontent.com/5795847/36027700-a0078850-0d9c-11e8-9e88-e4408d686d2b.png">

(BTW: Would be good that the "output" channel will be shown in the message popup.)

It's from the activated `go-langserver` (current `master` version https://github.com/sourcegraph/go-langserver/commit/c0ef041f)

```
[Error - 1:19:09 PM] Server initialization failed.
  Message: invalid root path "file://": must be file:/// URI
  Code: 0 
langserver-go: reading on stdin, writing on stdout
--> request #0: initialize: {"processId":40939,"capabilities":{},"trace":"off"}
<-- error #0: initialize: {"code":0,"message":"invalid root path \"file://\": must be file:/// URI","data":null}
--> request #1: shutdown: null
<-- error #1: shutdown: {"code":0,"message":"server must be initialized","data":null}
```

_Copied from original issue: Microsoft/vscode-go#1504_

**Comment by ramya-rao-a** [comment]
I can see this happening when opening a stand alone go file, but not when opening a folder. 
@slimsag @keegancsmith Looks like the language server fails when there is no folder open

**Comment by ramya-rao-a** [comment]
_From @keegancsmith on February 16, 2018 15:46_

Yeah right now go-langserver doesn't support not having a rootPath or rootURI. I'll see how easy it is to add, but we have in quite a lot of places baked in the assumption of a rootPath.

**Comment by ramya-rao-a** [comment]
_From @keegancsmith on February 27, 2018 14:57_

I'm unsure how well this would work, but we could just pretend that `rootPath = "/"`. For operations that inspect the `workspace` (like references), this would end up being very very costly. So it doesn't seem like the correct solution.

@ramya-rao-a what functionality is expected to work when there is no workspace? If we can rule out `references` and `workspace/symbols` that seems fine to me. If references are expected to work, in what scope? Just the current file / current directory / more (GOPATH?)

**Comment by ramya-rao-a** [comment]
We could start with just current directory and log the fact that we are doing so since going beyond is expensive.

**Comment by illenial** [comment]
When this is going to be fixed?

**Comment by keegancsmith** [comment]
It would probably be addressed as part of the work to use the new `go/packages`. See https://github.com/sourcegraph/go-langserver/issues/293

We welcome contributions.

**Comment by illenial** [comment]
@keegancsmith I have noticed that `IsURI` has some defect [here](https://sourcegraph.com/github.com/sourcegraph/go-langserver/-/blob/langserver/util/util.go#L72). According to [RFC 8089 §2](https://tools.ietf.org/html/rfc8089#section-2), `/`, `//` and `///` abide by as a file hierarchy part.

**Comment by keegancsmith** [comment]
Great, can ya send up a PR?
