### ISSUE TITLE
Diagnostics are highlighting non-ideal portion of error

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#29]
Spotted on Sublime using go-langserver:
https://cl.ly/1s2J0u231540

The error is really with AppURL.Scheme1, because Schem1 doesn't exist on whatever AppURL returns. But `conf` is underlined by the diagnostic.

For comparison (I think this is better behavior), on VSCode, things like this highlight the whole term:
https://cl.ly/040J3i0H2x2j

**Comment by keegancsmith** [comment]
@uforic in the example of the description, is it possible vscode is just highlighting the whole line? We can do similiar. Note the diagnostic information then isn't as accurate, but that isn't really an issue since we don't do much with the diags currently.

**Comment by uforic** [comment]
Doh - you're right: https://cl.ly/2J440M431o00 . Will close out and change for the plugin. Nice catch.
