### ISSUE TITLE
Formatting is broken on this example

### ISSUE THREAD

**Issue by maximbaz** [sourcegraph/go-langserver#296]
```go
package main
import "fmt"
func greet(name string) {
	fmt.Println("hello " + name)
}
```

With `goimports -e -w` I get the expected result:

```go
package main

import "fmt"

func greet(name string) {
	fmt.Println("hello " + name)
}
```

With the current master of go-langserver I get this result:

```go
package mainmport "fmt"
func greet(name string) {fmt.Println("hello " + name)
}
```

**Comment by dianedanlai** [comment]
I tried your example with the latest master and I cannot reproduce it(I am using Nuclide).

**Comment by maximbaz** [comment]
Thanks, I'm using kak-lsp and it could be a bug there, I'm just not sure how to verify this. Ping @ul :)

**Comment by ul** [comment]
This is indeed a kak-lsp bug. Looks like Kakoune doesn't support zero-width ranges, thus we need to treat them specially in kak-lsp.

**Comment by maximbaz** [comment]
OK thanks for confirming, let's continue in kak-lsp issue 😉
