### ISSUE TITLE
workspace/symbol (and probably workspace/reference) aren't constrained to things in the workspace

### ISSUE THREAD

**Issue by sqs** [sourcegraph/go-langserver#3]
They call buildutil.ExpandPatterns, which reads from the entire GOPATH/GOROOT, not just from the workspace. This breaks in vscode, because `h.init.RootImportPath` is not yet, and the GOPATH can have tons of packages unrelated to what's in the workspace.

Fix: filter to only pkgs whose dir is underneath the workspace rootPath

**Comment by keegancsmith** [comment]
@slimsag I think you did some stuff around this, know if this is still an issue?

**Comment by slimsag** [comment]
Ouch. I think this will likely still be a problem today. I don't think anything has changed w.r.t. this but I did not check yet.

**Comment by keegancsmith** [comment]
I don't really have a good feel for the importance of this bug. We could just filter the results afterwards, but that sounds like we are covering up an issue, but not fixing the performance implications. However, that fix is very easy so this is a nice and easy one to do on our next round of bug bashing. Probably best to save it until we prioritize small bugs again.

**Comment by sqs** [comment]
It's not important right now because it only happens when using this lang server in VSCode, not on Sourcegraph.

**Comment by keegancsmith** [comment]
I fixed this bug last week. Forgot we had an issue for it. https://github.com/sourcegraph/go-langserver/pull/82
