### ISSUE TITLE
How to disable the annoying "exported type Account should have comment or be unexported"?

### ISSUE THREAD

**Issue by jaggerwang** [sourcegraph/go-langserver#304]
This is really annoying as sometimes the exported type or method is only used inside the project and there is nothing need to comment out.

![image](https://user-images.githubusercontent.com/1255011/43818648-29726526-9b12-11e8-8b85-e2c66873318b.png)

**Comment by lloiser** [comment]
golang tries to enforce a certain code style. This is just one part of it.
https://github.com/golang/go/wiki/CodeReviewComments#doc-comments

Either add documentation to the exported types or methods or just don't export them if they are only used in the current package alone.

**Comment by jaggerwang** [comment]
OK, got it!

**Comment by keegancsmith** [comment]
Also I don't believe go-langserver reports those issues. That would be vscode-go integration with go-lint.
