### ISSUE TITLE
Support alternate linters

### ISSUE THREAD

**Issue by ckaznocha** [sourcegraph/go-langserver#314]
Hi!
Some users of my client are looking to use alternate linters for diagnostics, specifically [golangci/golangci-lint](https://github.com/golangci/golangci-lint). Could multiple linters be supported much like multiple formatters are now supported? I'd be happy to send a PR but I may not be able to get to it for a while.

For reference: https://github.com/ckaznocha/ide-go/issues/31

Thanks!

**Comment by keegancsmith** [comment]
Yeah this seems like a very reasonable feature request. One potential issue is the code in your editor is not necessarily the code on disk. So a requirement for integrating a linter would be it supporting linting a file, but us sending the contents of it over stdin/etc.

**Comment by ianlopshire** [comment]
I'm currently working on getting this implemented.

As far as I can tell, the language server doesn't currently implement any linting. The only diagnostics come from type checking errors. I'm not missing anything am I?

vscode-go currently supports `golint`, `gometalinter`, `megacheck`, `golangci-lint`, and `revive`. I think `gometalinter` and `golangci-lint` would be a good start.

**Comment by keegancsmith** [comment]
@ianlopshire thanks! Yes there is no support for linters currently. There are two routes you can take here:

- Include the above linters as libraries.
- Shell out to them.

Shelling out is likely the easiest and most maintainable approach for now. Unless of course a linter exposes a nice API to use.

**Comment by keegancsmith** [comment]
great. on save seems fine to me.

**Comment by keegancsmith** [comment]
We have support now for linters, and it is relatively easy to add support for more now. Thanks @ianlopshire!
