### ISSUE TITLE
Unable to auto complete the modules

### ISSUE THREAD

**Issue by seagle0128** [sourcegraph/go-langserver#319]
I upgraded to the latest `go-langserver`, and found the local modules including vendor/ and others (e.g. common/, lib/ etc.) couldn't autocomplete. I reverted to d0a69e92f6bdce74c7acdd59fdca57cca2a9587e, and it works well. I doubt the issue is related to 28e52ba21ccbf22a81d274d5cfdd2179cac04b79. 

Running `go1.10.4 darwin/amd64`

**Comment by seagle0128** [comment]
Actually I found there is no output in $GOPATH/pkg, but should be there. 
This issue is related to https://github.com/mdempsky/gocode/issues/47, I believe, since `go install vendor/...` fix it manually. Please follow up.

**Comment by keegancsmith** [comment]
cc @anjmao who recently updated our vendored gocode.

**Comment by anjmao** [comment]
I'm using vscode and there is no such problem. Probably because vscode-go automatically builds to pkg. Even if I remove pkg folder on save I get pkg back. vscode output
```
Finished running tool: /usr/local/go/bin/go build -i -o /var/folders/jc/1233a/T/go-code-check.1693675331 do/cmd/server
Finished running tool: /usr/local/go/bin/go vet ./...
```

In go-langserver gocode binary cache is enabled by default. The only solution I see if you are not using vscode is to build vendor manually since gocode should not be responsible for doing that, but editor extension should.

**Comment by seagle0128** [comment]
@anjmao did you try cleaning all pkg and cache? 
```shell
go clean -cache
rm -rf $GOAPTH/pkg
```

**Comment by anjmao** [comment]
@seagle0128 Which editor are you using is it atom + go-plus?

**Comment by seagle0128** [comment]
@anjmao I am using Emacs + lsp-mode.

**Comment by seagle0128** [comment]
I tried [eglot](https://github.com/joaotavora/eglot) which is another lsp client of Emacs. The same issue.

**Comment by udaykumar106** [comment]
Same problem with neovim + deoplete + LanguageClient-neovim. As @seagle0128 says, if I revert go-langserver to [](https://github.com/sourcegraph/go-langserver/commit/28e52ba21ccbf22a81d274d5cfdd2179cac04b79), everything works.

**Comment by keegancsmith** [comment]
We depend on upstream gocode, so until mdempsky/gocode#47 is solved, I don't think we have a solution. Something we could possible do is run `go install` as part of go-langserver doing diagnostics.

**Comment by alecthomas** [comment]
They just closed that issue with "won't fix"...

**Comment by seagle0128** [comment]
I don't understand why. It's a regression issue IMO.

**Comment by seagle0128** [comment]
https://github.com/mdempsky/gocode/issues/47 has been fixed.

**Comment by seagle0128** [comment]
Thanks!

**Comment by keegancsmith** [comment]
Thanks @imjustfly!

**Comment by udaykumar106** [comment]
Thank you
