### ISSUE TITLE
Hover returns no results on function-local variable

### ISSUE THREAD

**Issue by b0o** [sourcegraph/go-langserver#330]
I'm not sure if this the intended behavior or not, but I can't get hover information for variables defined within a function body. I often want to quickly see the type for the identifier under my cursor, but this only seems to work for identifiers defined outside the function.

Client: [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)

Example (hover was activated when the cursor moved to the location inside the square brackets, i.e. `[s]`):

```go
package main

import "log"

func main() {
	s := "This is a string"
	log.Println([s])
}
```

Log output:
```
11:55:31 INFO main src/languageclient.rs:966 Begin textDocument/hover
11:55:31 INFO main src/languageclient.rs:48 gather_args: [LanguageId, Filename, Line, Character, Handle] = [String("go"), String("/home/maddy/test/go/main.go"), Number(6), Number(13), Bool(false)]
11:55:31 INFO main src/vim.rs:92 => Some("go") {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":13,"line":6},"textDocument":{"uri":"file:///home/maddy/test/go/main.go"}},"id":201}
11:55:31 INFO reader-go src/vim.rs:380 <= Some("go") {"id":201,"result":{"contents":[]},"jsonrpc":"2.0"}
11:55:31 INFO main src/vim.rs:92 => None {"jsonrpc":"2.0","result":{"contents":[]},"id":69}
```

You can see that the response to the hover request is empty:
```json
{"id":201,"result":{"contents":[]},"jsonrpc":"2.0"}
```

As a counter example, here is the behavior when the variable is defined outside the function, and is akin to the behavior I'd expect from the previous example (again, hover was activated when the cursor moved to the location inside the square brackets, i.e. [s]):

```go
package main

import "log"

var s = "This is a string"

func main() {
	log.Println([s])
}
```

```
12:08:47 INFO main src/languageclient.rs:966 Begin textDocument/hover
12:08:47 INFO main src/languageclient.rs:48 gather_args: [LanguageId, Filename, Line, Character, Handle] = [String("go"), String("/home/maddy/test/go/main.go"), Number(7), Number(13), Bool(false)]
12:08:47 INFO main src/vim.rs:92 => Some("go") {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":13,"line":7},"textDocument":{"uri":"file:///home/maddy/test/go/main.go"}},"id":97}
12:08:47 INFO reader-go src/vim.rs:380 <= Some("go") {"id":97,"result":{"contents":[{"language":"go","value":"var s = \"This is a string\""}]},"jsonrpc":"2.0"}
12:08:47 INFO main src/vim.rs:92 => None {"jsonrpc":"2.0","result":{"contents":[{"language":"go","value":"var s = \"This is a string\""}]},"id":93}
```

```json
{"id":97,"result":{"contents":[{"language":"go","value":"var s = \"This is a string\""}]},"jsonrpc":"2.0"}
```

---

If this is the intended behavior, is there a reason for it?

**Comment by keegancsmith** [comment]
Nope that is not intentional. Will take a look.

**Comment by b0o** [comment]
@keegancsmith Any progress on this?

**Comment by b0o** [comment]
I actually determined this was a configuration issue on my end, I needed to disable the binary pkg cache option: `go-langserver -usebinarypkgcache=0`.

**Comment by engineeror** [comment]
I have the exact same problem, it only works when variable is global. Sadly, `-usebinarypkgcache false` does nothing.

@keegancsmith, should I open a new issue?
