### ISSUE TITLE
rename command not in initialization response

### ISSUE THREAD

**Issue by Dbz** [sourcegraph/go-langserver#342]
My language client doesn't know go-langserver can perform renames because go-langserver doesn't add the capability in the initialize response. Would we be able to add that?

I would be happy to make a PR myself if someone can help point me in the right direction. (I just started learning Go this past week and completed a Udemy course on it, and this would be a fun first PR.)

**Comment by Dbz** [comment]
Oh perfect 🎉  I'll make a PR as soon as I get home from work

**Comment by Dbz** [comment]
Had to steal my PR @fannheyward ! I'm teasing. I'm glad it got in and that I could help with creating the issue :)

**Comment by fannheyward** [comment]
@Dbz sorry for steal your PR. Just see that you have not submit for hours, so I made it.

**Comment by Dbz** [comment]
I know, I just got home from work. But it is OK - I was just teasing. What is important is that we help each other build better software, and we're doing that. It doesn't matter if I do it, or if you do it. I'm glad there are more people out there who want to improve the project 👍

**Comment by slimsag** [comment]
Haha I didn't notice the author was different, my bad :P FWIW CI just detected a (unrelated) data race  if anyone wants to look into that 😜https://github.com/sourcegraph/go-langserver/issues/344
