### ISSUE TITLE
Language Server not registering providers since the last couple of commits

### ISSUE THREAD

**Issue by ramya-rao-a** [sourcegraph/go-langserver#356]
With https://github.com/sourcegraph/go-langserver/commit/8c25906a7dbc904acc96b5435ec42fa5da8b232c, the language server is not registering any of the providers correctly.

When using VS Code, this translates to not seeing any of the features from the language server. 
Prior to the above commit, the language server works as expected. 

Below is the trace (when everything works i.e prior to https://github.com/sourcegraph/go-langserver/commit/8c25906a7dbc904acc96b5435ec42fa5da8b232c), when opening a file in a new VS Code window and hovering on a symbol

![image](https://user-images.githubusercontent.com/16890566/51444943-848bf800-1cb3-11e9-954f-df5ec0e08155.png)

Below is the trace, (after https://github.com/sourcegraph/go-langserver/commit/8c25906a7dbc904acc96b5435ec42fa5da8b232c) when opening a file in a new VS Code window and hovering on a symbol. 
It is the same as the part above the red line in the previous picture

![image](https://user-images.githubusercontent.com/16890566/51444907-04fe2900-1cb3-11e9-86eb-403a8d446f3e.png)

Below is the error in the console from the vscode-languageclient

![image](https://user-images.githubusercontent.com/16890566/51444922-337c0400-1cb3-11e9-86f7-5e5c474483bf.png)

**Comment by keegancsmith** [comment]
cc @chrismwendt
