### ISSUE TITLE
What unit does go-langserver use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [sourcegraph/go-langserver#362]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by slimsag** [comment]
We currently use unicode codepoints. Given the spec said that `Position` is character-based (it is a bit ambiguous what a character is) the thinking was that it was safe to assume it was a unicode codepoint. I can see why grapheme cluster indexes would also make sense.

We also currently do not support any document encoding except UTF-8, I believe(?), so we are probably limited to UTF-8 codepoints.

**Comment by Avi-D-coder** [comment]
@slimsag thanks
