### ISSUE TITLE
Server must be initialized ,How to use a go-langserver in a IDE

### ISSUE THREAD

**Issue by jamwulei** [sourcegraph/go-langserver#375]
Hello   a few great gods ,I  fall into some troubles，can you help me ?
 @keegancsmith   @slimsag   @sqs  @chrismwendt 

Now,I have download the code of go-langserver master .
    after I config the IP port and mode in the code (127.0.0.1:4389 tcp), I try to send a  http request by postman with method initialize 、jsonrpc 2.0  ,I get the response with the corrent result which contain the LSP`s capabilities .
first question :when I send a request by postman with method others（ex:textDocument/hover）,the error  occurred "server must be initialized" , http server is a  short tcp connection，I do not know how to transfer the init params .
second question : I do not know how to use this LSP in IDE ,I just build a service by this LSP server ,but how can config it to the IDE which I want to use ?

**Comment by chrismwendt** [comment]
go-langserver speaks a protocol called LSP which requires a message passing communication style. HTTP only provides a request/response communication style. TCP and WebSockets provide a message passing communication style. Postman (as far as I know) only supports HTTP, which means you can't use Postman to directly interact with go-langserver.

To use go-langserver in VS Code, install the Go extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go and follow the instructions in the section "Settings to control the use of the Go language server".

For Vim, check out https://github.com/prabirshrestha/vim-lsp

**Comment by jamwulei** [comment]
I have tried to use my custom go client to connect go-langserver by lsp protocol, but after the server successfully obtained the message, it prompted the connection to close, in fact, my client is only closewrite，I check the server`s code, but I do not find why ,can you give me a simple example a bout go client which can connect to go-langserver.

**Comment by chrismwendt** [comment]
What command line arguments are you passing? go-langserver will shut down immediately after the stdio pipes close if run with `-mode=stdio`.

lsp-adapter is a project that acts as a proxy between a client and a server, and here's a good place to start to see how to communicate with go-langserver https://sourcegraph.com/github.com/sourcegraph/lsp-adapter@8c9f26cef0978ba96cf1fdca7e24546a3cd5384a/-/blob/proxy.go#L144-169

**Comment by jamwulei** [comment]
@ChristianWitts thanks for your sincere reply ,I have get another way to do it .
