### ISSUE TITLE
Does goLangServer support go modules

### ISSUE THREAD

**Issue by byteshiva** [sourcegraph/go-langserver#378]
I have installed go 1.13.4 and using MS vscode, it complains and points to install google Lang Server. Am I missing something here.

"The language server from Sourcegraph is no longer under active development and it does not support Go modules as well. Please install and use the language server from Google or disable the use of language servers altogether."

ps:-
FYI.. go please implements go language server.
**gopls** (pronounced: "go please") is the official language server for the Go language.
https://github.com/golang/tools/blob/master/gopls/doc/vscode.md

**Comment by chrismwendt** [comment]
go-langserver does not support Go modules.

Use https://github.com/golang/tools/blob/master/gopls/doc/vscode.md instead.
