### ISSUE TITLE
Find-definitions doesn't consider test packages

### ISSUE THREAD

**Issue by knz** [sourcegraph/go-langserver#379]
Go supports placing `xxx_test.go` files in a package `foo` where the package definition is `package foo_test`

References to symbols from such test files are not found by lsp find-definitions.

**Comment by keegancsmith** [comment]
Hi @knz I'm surprised this isn't working for you, I believe we have explicit support for xtests. Is it possible you may be using gopls (or another language server). Note: development of a langserver for your editor has been going on in the gopls project. This repo has mostly gone into maintenance mode only.

**Comment by knz** [comment]
Oh yes you are correct I am using gopls. I did not know this was a different project.
