### ISSUE TITLE
What's the difference between this project and sourcegraph/go-lsp

### ISSUE THREAD

**Issue by HaoboGu** [sourcegraph/go-langserver#381]
Hi all, 

I am looking for a go-lsp implementation which can be used to serve other languages like javascript. I found this project and [sourcegraph/go-lsp](https://github.com/sourcegraph/go-lsp). Is there anyone who can tell me which project should I use?  Thanks very much!

**Comment by unknwon** [comment]
Hi, based on the README, I think https://github.com/sourcegraph/go-lsp only contains types, and this repository does the actual thing.
