### ISSUE TITLE
File paths containing `@` should be valid

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/go-langserver#39]
https://sourcegraph.com/github.com/sourcegraph/go-langserver@7e635d805440326f635a8dbf61c658d4a21a22b5/-/blob/langserver/fs.go#L85-87

**Comment by keegancsmith** [comment]
@beyang I lost context on why this is bad. Do you remember the example you gave me? How important is this?

**Comment by beyang** [comment]
You might have file paths like https://sourcegraph.com/github.com/angular/angular@75d1617b6329f82e0dd8ee61164e1790a69b3082/-/blob/modules/@angular/core/index.ts#L19 that have an '@' ("@angular").

I can't remember an instance of this in Go, but it should at least be permissible.

**Comment by keegancsmith** [comment]
Yeah I assume if that repo actually had go code in it, we may trigger a panic which is a bug.
