### ISSUE TITLE
Ability to test go-langserver homebrew formula

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/go-langserver#41]
As described in [Add a test to the formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#add-a-test-to-the-formula) section, we need to add a basic test to make sure homebrew formula is successfully built and working. Ideally, would be nice to pass some file with HTTP messages as program's input and compare the output with the expected one. Some flag that returns 0 exit code is fine too.

I need it to complete [I can install the Go LSP on my Mac using Homebrew ](https://trello.com/c/1jjYLVBC/1-i-can-install-the-go-lsp-on-my-mac-using-homebrew-1)

CC @mejamiewilson

**Comment by keegancsmith** [comment]
@alexsaveliev you can replicate this test with a bit of bash and netcat. https://github.com/sourcegraph/go-langserver/blob/master/langserver/integration_test.go

**Comment by alexsaveliev** [comment]
@keegancsmith thanks, made it (#44)! 

Note to self: 
- have a delay after sending `initialize` and before sending `exit` requests, otherwise you may see no data in stdio mode
