### ISSUE TITLE
Hint if a symbol supports find all references

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/go-langserver#45]
Currently the sourcegraph frontend has a hack to prevent showing find all references for primitive types when hovering over them, since the server does not support it / there is minimal value for doing so. We want to remove the hack, so we should find a nice way to do so. Options:

* Add another field to the contents array to indicate the type / if we support find all refs
* A special field in the hover response
* Ignore this problem, and indicate we can find all refs on primitive go types.

![image](https://cloud.githubusercontent.com/assets/187831/20827608/cadac974-b87b-11e6-87ff-d968326992cd.png)

![image](https://cloud.githubusercontent.com/assets/187831/20827621/d6545810-b87b-11e6-8de8-92e816310a7d.png)

**Comment by sqs** [comment]
@keegancsmith: @chexee is exploring better ways to make references (and other context-menu actions) accessible in the UI. I can think of enough ways she could design it that wouldn't need this hint that it's worth waiting for her on this.

**Comment by keegancsmith** [comment]
Ok, I'll leave this open for a bit just so @nicot can respond (he mentioned this to me on slack). But I agree, I'd rather just close this out since the right click to view references on hover is a hack as well + if you right click on a primitive we show the references option anyways.

**Comment by nicot** [comment]
Yeah it's a weird situation. My thinking is that the info sent back for builtins is so minimal it isn't useful, so we should just remove it from the hover response.

Do we have an estimate of when we're going to improve the UX of the actions that are only available on right click?

**Comment by sqs** [comment]
Let's move this to the Sourcegraph repo.

**Comment by keegancsmith** [comment]
I'm gonna close this out. I assume adding something special to the LSP protocol for hacks that we do on our side is less than ideal, and is better solved with us innovating on the UI since there are lots of other "types" we want to prevent the same issue.
