### ISSUE TITLE
Support for Glide and GoDep vendoring

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#49]
See `https://github.com/uforic/simple_go/blob/master/simple.go`

If you click on Router, it goes to the /vendor folder - desired behavior: an option of whether to go to mux.go in /vendor, or to the correct revision of the library @ `0eeaf839`, not the HEAD of mux which is now at  `757bef9`

Party!

**Comment by keegancsmith** [comment]
FYI for others looking, this was closed since this would be the responsibility of the build server, not the language server.
