### ISSUE TITLE
off by one error observed between workspace/symbol and textDocument/definition calls

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#7]
On our code base, run textDocument/definition with the following args:
textDocument:"file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/app/app.go"
position: line: 26, character: 39

I get back the following symbol:
uri: "file:///usr/local/go/src/net/http/server.go"
range: 76/5 -> 76/11

Call workspace symbols on our code base, with the query "Handler." The token we are looking for, in file:///usr/local/go/src/net/http/server.go, has this range:
76/5 -> 76/12

Still learning up on LSP, but the above seems like it could be an off by one error! The reason I'd like these to be equal is I'm calling deep_equal on all the ranges returned by workspace/symbol to try and find the one corresponding to textDocument/definition .

**Comment by keegancsmith** [comment]
Nice find! End of symbol ranges I don't think we have that well defined. ie inclusive vs exclusive ranges. Luckily we have lots of unit tests to make it easy to fix :)

**Comment by keegancsmith** [comment]
I forgot about this, will follow up when we do a bug bash.

**Comment by keegancsmith** [comment]
@felixfbecker you are my favourite LSP expert. Is a range inclusive or exclusive of the `End`? I believe it is End after some other work I did recently involving `textDocument/formatting`, just want to confirm.

**Comment by keegancsmith** [comment]
Nevermind me, it is in the spec.
> Therefore the end position is exclusive
