### ISSUE TITLE
vscode: Support Workspace Symbol Search

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/go-langserver#70]
Our symbol search currently does not seem to work when used via vscode. It only works in production sourcegraph.com due to some extra translations our build server does. It should work in vscode.

**Comment by keegancsmith** [comment]
Our `workspace/symbols` searches the whole `GOPATH`. What is the expected behaviour from vscode? I assume we would want to limit it to rootPath only? cc @ramya-rao-a

**Comment by keegancsmith** [comment]
Re-opening to get feedback about GOPATH.

**Comment by rothfels** [comment]
@keegancsmith seems gratuitous to include every symbol found in your GOPATH. Also, the current vscode behavior is to only show symbols in your workspace: https://cl.ly/1q2j3I1U3v18

**Comment by rothfels** [comment]
https://cl.ly/2V1L3j2y3137

**Comment by keegancsmith** [comment]
@rothfels thanks. I'll improve that behaviour before closing this issue.

@slimsag just to pre-empt my dive into symbols code, it should be easy to filter to just the current workspace right? And filter before inspecting something, not after (ie don't just throw the results away).

**Comment by keegancsmith** [comment]
#82 resolves symbol search looking at the whole GOPATH. On my local machine vscode symbol and file outline go from half a minute to instant.
