### ISSUE TITLE
codegen: map to vscode-languageserver-node/client

### ISSUE THREAD

**Issue by mbana** [sourcegraph/go-langserver#8]
hi,

is it possible to generate the defs from this repo somehow?
https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocol.ts#L140
Or better yet ask MS to make a generic definition lib that can used to generate the code for ur language.

**npm packages:**

``` json
    "vscode-languageclient": "^2.5.0",
    "vscode-jsonrpc": "^2.4.0",
    "vscode-languageserver-types": "^1.0.4"
```

cheers,

**Comment by keegancsmith** [comment]
@mbana Why generate from there? It doesn't really change often enough that doing it by hand is annoying. Also we extend the spec in some places, so for now closing as a wontfix.
